### ISSUE TITLE
Need to add proper error messages and handle native exceptions

### ISSUE THREAD

**Issue by dilanSachi** [ballerina-platform/ballerina-library#4014]
**Description:**
When the proto path is not defined for files with imports, an exception is thrown instead of a descriptive error message.

```
Downloading the protoc executor file - protoc-3.9.1-linux-x86_64.exe
Download successfully completed. Executor file path - /tmp/protoc-3.9.1-linux-x86_64.exe
Successfully extracted the library files.
Jan 24, 2023 9:01:41 PM io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd generateBalFile
SEVERE: An error occurred when generating the proto descriptor.
io.ballerina.stdlib.grpc.protobuf.exception.CodeGeneratorException: Invalid command syntax. Stream closed
	at io.ballerina.stdlib.grpc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:110)
	at io.ballerina.stdlib.grpc.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:83)
	at io.ballerina.stdlib.grpc.protobuf.cmd.DescriptorsGenerator.generateRootDescriptor(DescriptorsGenerator.java:148)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:251)
	at io.ballerina.stdlib.grpc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:165)
	at java.base/java.util.Optional.ifPresent(Unknown Source)
	at io.ballerina.cli.launcher.Main.main(Main.java:51)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(Unknown Source)
	at java.base/java.io.BufferedInputStream.read(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at java.base/sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.base/java.io.InputStreamReader.read(Unknown Source)
	at java.base/java.io.BufferedReader.fill(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at java.base/java.io.BufferedReader.readLine(Unknown Source)
	at io.ballerina.stdlib.grpc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:105)
	... 6 more

An error occurred when generating the proto descriptor. Invalid command syntax. Stream closed
```

**Comment by daneshk** [comment]
This is fixed. Hence closing the issue
