### ISSUE TITLE
Program crashes with NPE

### ISSUE THREAD

**Issue by MohamedSabthar** [ballerina-platform/ballerina-library#4273]
**Description:**
$Subject

**Steps to reproduce:**
consider the following code 
```ballerina
import ballerina/sql;
import ballerina/io;

isolated function printer() {
    int id = 1;
    sql:ParameterizedQuery query = `SELECT * FROM authors WHERE id IN (${id})`;
    io:println(query);
}

public function main() returns error? {

    future<()>[] futures = [];
    foreach var item in 0..<10 {
        future<()> res = start printer();
        futures.push(res);
    }

    foreach var 'future in futures {
        check wait 'future;
    } 
}
```

the above program crashes with following output

```
SELECT * FROM authors WHERE id IN (1)
SELECT * FROM authors WHERE id IN (1)
SELECT * FROM authors WHERE id IN (1)
SELECT * FROM authors WHERE id IN (1)
SELECT * FROM authors WHERE id IN (1)
SELECT * FROM authors WHERE id IN (1)
[2023-03-28 15:57:15,714] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,714] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,789] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,714] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,714] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,792] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,790] SEVERE {b7a.log.crash} - class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app')
        at sql.printer(sql.bal:8)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,788] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,795] SEVERE {b7a.log.crash} - class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app')
        at sql.printer(sql.bal:8)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,792] SEVERE {b7a.log.crash} - null 
java.lang.NullPointerException
        at io.ballerina.runtime.api.utils.StringUtils.getStringValue(StringUtils.java:210)
        at io.ballerina.stdlib.io.nativeimpl.PrintUtils.println(PrintUtils.java:69)
        at ballerina.io.1.print.externPrintln(print.bal:147)
        at ballerina.io.1.print.println(print.bal:65)
        at sql.printer(sql.bal:7)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,796] SEVERE {b7a.log.crash} - class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app')
        at sql.printer(sql.bal:8)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,799] SEVERE {b7a.log.crash} - class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app')
        at sql.printer(sql.bal:8)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
[2023-03-28 15:57:15,800] SEVERE {b7a.log.crash} - class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app') 
java.lang.ClassCastException: class ballerina.io.1.frames.$frame$PrintableClassImpl_toString cannot be cast to class frames.$frame$printer (ballerina.io.1.frames.$frame$PrintableClassImpl_toString and frames.$frame$printer are in unnamed module of loader 'app')
        at sql.printer(sql.bal:8)
        at sql.$printer$lambda$_0$(sql.bal:14)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:324)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:291)
        at java.base/java.lang.Thread.run(Thread.java:829)
 
```

**Affected Versions:**
tested on `Ballerina 2201.4.0`

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**

**Comment by ruchiralakshan123** [comment]
Hi @daneshk, 

I would like to work on this issue. Could you please assign it to me?
