### ISSUE TITLE
Improve diagnostics for invalid proto files

### ISSUE THREAD

**Issue by pubudu91** [ballerina-platform/ballerina-library#4656]
When the proto file is invalid, the `grpc` command crashes. It would be better if we can have proper error messages for the failures. 

For example, in my case, the issue was I hadn't defined a type that I had used in another type:
```proto3
message PaginatedUser {
    int64 count = 1;
    repeated User list = 2;
    Pagination pagination = 3;
}
```
The `User` wasn't defined in the file. The output from the `grpc` command was as follows:
```
bal grpc --input resources/user_service.proto
Downloading the protoc executor file - protoc-3.21.7-osx-x86_64.exe
Download successfully completed. Executor file path - /var/folders/_w/76qx789d5hj633snw3c8fswr0000gp/T/protoc-3.21.7-osx-x86_64.exe
Successfully extracted the library files.
Jul 12, 2023 11:27:00 AM io.ballerina.protoc.protobuf.cmd.GrpcCmd generateBalFile
SEVERE: An error occurred when generating the proto descriptor.
io.ballerina.protoc.protobuf.exception.CodeGeneratorException: Invalid command syntax. Stream closed
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:110)
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.generateDescriptor(BalFileGenerationUtils.java:83)
	at io.ballerina.protoc.protobuf.cmd.DescriptorsGenerator.generateRootDescriptor(DescriptorsGenerator.java:148)
	at io.ballerina.protoc.protobuf.cmd.GrpcCmd.generateBalFile(GrpcCmd.java:251)
	at io.ballerina.protoc.protobuf.cmd.GrpcCmd.execute(GrpcCmd.java:165)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.ballerina.cli.launcher.Main.main(Main.java:53)
Caused by: java.io.IOException: Stream closed
	at java.base/java.io.BufferedInputStream.getBufIfOpen(BufferedInputStream.java:176)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:342)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:181)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at io.ballerina.protoc.protobuf.utils.BalFileGenerationUtils.handleProcessExecutionErrors(BalFileGenerationUtils.java:105)
	... 6 more

An error occurred when generating the proto descriptor. Invalid command syntax. Stream closed
```
This has 2 problems:
- The `grpc` command has crashed. This is not a good look to have the runtime crash.
- No explanation for the failure. Only says invalid command syntax.

**Comment by Abhi132004** [comment]
Hii ballerina team , I would like to work on this task

**Comment by Abhi132004** [comment]
done with the task kindly check.

**Comment by ThisaruGuruge** [comment]
Hi @Abhi132004! 🚀

We value your contributions and look forward to collaborating with you.
To help you get started, here are some essential resources:

- Understanding Ballerina Platform: Learn what Ballerina is all about: [Ballerina Platform](https://github.com/ballerina-platform/ballerina-release/blob/master/CONTRIBUTING.md)
- How to Contribute: Read our contributing guidelines to understand how you can contribute effectively: [Contribution Guide](https://github.com/ballerina-platform/ballerina-lang/blob/master/CONTRIBUTING.md)
- Learn Ballerina: If you're new to Ballerina or want to enhance your skills, our official website offers a wealth of learning resources: [Learn Ballerina](https://ballerina.io/learn/)
- Get Help and Connect: Join our Discord community to chat with fellow Ballerina enthusiasts and get assistance: [Ballerina Discord](https://discord.com/invite/ballerinalang)

Remember, no contribution is too small, and your feedback is invaluable. Feel free to ask questions, propose ideas, or report issues. Together, we can make Ballerina even better!

Happy coding! 🎉

**Comment by ThisaruGuruge** [comment]
> done with the task kindly check.

Hi @Abhi132004 

You have to do the fix and send a PR to the ballerina-platform organization repository. Please look into the resources provided before working on the issue. Feel free to ask any questions you have regarding this issue.

**Comment by dilanSachi** [comment]
Hi @Abhi132004 . Regarding your PR, this is something different from what we expect in this issue. We need to handle the error from the tool level instead of ballerina program level. When a user runs the tool to generate a Ballerina stub file, it does not run inside a Ballerina program, It's a separate Java program which starts it's execution from here [1]. Feel free to ask questions if anything is not clear.

[1] https://github.com/ballerina-platform/protoc-tools/blob/main/protoc-cli/src/main/java/io/ballerina/protoc/protobuf/cmd/GrpcCmd.java#L128

**Comment by Abhi132004** [comment]
@dilanSachi fine,  So I need to make change in code itself or I will submit a new PR as a new file?

**Comment by dilanSachi** [comment]
> @dilanSachi fine, So I need to make change in code itself or I will submit a new PR as a new file?

You need to change our existing codebase to do this change and send a new pr to the repo

**Comment by Abhi132004** [comment]
@dilanSachi here's the updated file ,
This modified code catches exceptions that can occur during the execution of methods such as getProtoFiles and generateBalFile. In contrast, the original code doesn't catch these exceptions explicitly and might lead to unexpected crashes.

**Comment by Abhi132004** [comment]
The expected changes from the reviewers in patch1 implemented successfully

**Comment by Abhi132004** [comment]
Code readability improved as mentioned

**Comment by Abhi132004** [comment]
Code readability improved as mentioned, code updated such that it dosen't exceed 120 words limit , patch-3 PR open @ThisaruGuruge @keizer619 @dilanSachi

**Comment by Abhi132004** [comment]
The changes mentioned is implemented in the same pr(patch 3) @dilanSachi

**Comment by Abhi132004** [comment]
All mentioned changes are implemented

**Comment by Ishad-M-I-M** [comment]
Hi @keizer619 , Can I get this issue assigned to me

**Comment by mohammadruman** [comment]
Hi @keizer619  can you assign me? I would like to work on this issue.

**Comment by keizer619** [comment]
@mohammadruman Are you working on this?  If not we can let @Ishad-M-I-M to take this

**Comment by ARYPROGRAMMER** [comment]
hey @pubudu91 , sorry for the ping in advance but can I get this issue assigned. I would like to actually contribute a high quality handler for this. Thanks

**Comment by ThisaruGuruge** [comment]
Hi @ARYPROGRAMMER 

Thank you for your interest on contributing to Ballerina. The issue has been assigned to you now. Please let us know if you need any help.

You can join the [Ballerina Discord Server](https://discord.gg/ballerinalang) where you can ask anything related to Ballerina. There's a dedicated **Hacktoberfet-help** channel where you can ask Hacktoberfest related questions.

**Comment by ARYPROGRAMMER** [comment]
> Hi [@ARYPROGRAMMER](https://github.com/ARYPROGRAMMER)
> 
> Thank you for your interest on contributing to Ballerina. The issue has been assigned to you now. Please let us know if you need any help.
> 
> You can join the [Ballerina Discord Server](https://discord.gg/ballerinalang) where you can ask anything related to Ballerina. There's a dedicated **Hacktoberfet-help** channel where you can ask Hacktoberfest related questions.

Hi @ThisaruGuruge I already have a pr at https://github.com/ballerina-platform/protoc-tools/pull/72

**Comment by ARYPROGRAMMER** [comment]
> Hi [@ARYPROGRAMMER](https://github.com/ARYPROGRAMMER)
> 
> Thank you for your interest on contributing to Ballerina. The issue has been assigned to you now. Please let us know if you need any help.
> 
> You can join the [Ballerina Discord Server](https://discord.gg/ballerinalang) where you can ask anything related to Ballerina. There's a dedicated **Hacktoberfet-help** channel where you can ask Hacktoberfest related questions.

I think quite a long time since i raised the pr. please check it once @ThisaruGuruge 

https://github.com/ballerina-platform/protoc-tools/pull/72

**Comment by ThisaruGuruge** [comment]
@daneshk can you please review this PR?

**Comment by ARYPROGRAMMER** [comment]
> [@daneshk](https://github.com/daneshk) can you please review this PR?

just a reminder, its been too long

cc: @ThisaruGuruge and @daneshk
