### ISSUE TITLE
openAPI tool gives an error when trying with a yaml of open api v3.1.0

### ISSUE THREAD

**Issue by lalaji** [ballerina-platform/ballerina-library#5940]
**Description:**
I'm trying to generate bal code from openAPI tool for a financial API yaml which is on open api v3.1.0 and tool gave the below error.

Error is "Error occurred when generating service for OpenAPI contract at fdxapi.core.yaml. OpenAPI definition has errors: 
attribute openapi is not of type `object`"

io.swagger.v3.parser.util.DeserializationUtils$SnakeException: Exception safe-checking yaml content  (maxDepth 2000, maxYamlAliasesForCollections 2147483647)
	at io.swagger.v3.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:483)
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:493)
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:422)
	at io.swagger.v3.parser.util.DeserializationUtils.readYamlTree(DeserializationUtils.java:258)
	at io.swagger.v3.parser.util.DeserializationUtils.deserializeIntoTree(DeserializationUtils.java:172)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:168)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:107)
	at io.swagger.parser.OpenAPIParser.readContents(OpenAPIParser.java:29)
	at io.ballerina.openapi.core.GeneratorUtils.getOpenAPIFromOpenAPIV3Parser(GeneratorUtils.java:502)
	at io.ballerina.openapi.core.GeneratorUtils.normalizeOpenAPI(GeneratorUtils.java:802)
	at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateBallerinaService(BallerinaCodeGenerator.java:408)
	at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateService(BallerinaCodeGenerator.java:246)
	at io.ballerina.openapi.cmd.OpenApiCmd.generateServiceFile(OpenApiCmd.java:393)
	at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:294)
	at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:197)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at io.ballerina.cli.launcher.Main.main(Main.java:58)
Caused by: mapping values are not allowed here
 in 'string', line 2, column 8:
    openapi: 3.1.0
           ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:902)
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:391)
	at org.yaml.snakeyaml.scanner.ScannerImpl.peekToken(ScannerImpl.java:261)
	at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentEnd.produce(ParserImpl.java:280)
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:162)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:57)
	at org.yaml.snakeyaml.comments.CommentEventsCollector$1.peek(CommentEventsCollector.java:43)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:136)
	at org.yaml.snakeyaml.comments.CommentEventsCollector.collectEvents(CommentEventsCollector.java:116)
	at org.yaml.snakeyaml.composer.Composer.composeScalarNode(Composer.java:241)
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:205)
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:131)
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:157)
	at io.swagger.v3.parser.util.DeserializationUtils$CustomSnakeYamlConstructor.getSingleData(DeserializationUtils.java:460)
	... 16 more

**Steps to reproduce:**
Followed steps as in https://ballerina.io/learn/openapi-tool/

**Affected Versions:**

Ballerina 2201.8.4 (Swan Lake Update 8)
Language specification 2023R1
Update Tool 1.4.2

**OS, DB, other environment details and versions:**

**Related Issues (optional):**

**Suggested Labels (optional):**

**Suggested Assignees (optional):**
hansani@wso2.com

**Comment by lnash94** [comment]
I tried using the 2201.8.4 version and received the following error log, which differs from the one above. The cause of the error[1] is missing component details in the YAML file. shall we have the all swagger files related to it?

Error log [1]
```
Jan 12, 2024 11:59:10 AM io.swagger.v3.parser.reference.ReferenceVisitor resolveSchemaRef
SEVERE: Error resolving schema ./fdxapi.components.yaml#/components/schemas/DateString
java.lang.RuntimeException: Could not find fdxapi.components.yaml on the classpath
	at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath(ClasspathHelper.java:33)
	at io.swagger.v3.parser.reference.Visitor.readClasspath(Visitor.java:72)
...
```

However, after analyzing both logs, it appears that these errors occurred due to issues within the provided YAML file. The Swagger parser identifies the parser issue itself, as mentioned above log in the issue description.

**Comment by lnash94** [comment]
Removed the `bug` lable and closed the issue because this was worked as expected.

**Comment by lalaji** [comment]
Thanks a lot!
