### ISSUE TITLE
Received `NullKeySerializer` issue when generating OAS for Ballerina service  

### ISSUE THREAD

**Issue by lnash94** [ballerina-platform/ballerina-library#6062]
**Description:**
Given service[1] has the post method with the qualified record type, due to this type code generation has ended up with the below error[2]

[1]Sample service:
```ballerina
service /books on new http:Listener(9090) {
   isolated resource function post .(store:BookInsert book) returns int|error? {
       int[] bookIds = check sClient->/books.post([book]);
       return bookIds[0];
   }
```
[2] Error stack
```
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.swagger.v3.oas.models.OpenAPI["paths"]->io.swagger.v3.oas.models.Paths["/"]->io.swagger.v3.oas.models.PathItem["post"]->io.swagger.v3.oas.models.Operation["requestBody"]->io.swagger.v3.oas.models.parameters.RequestBody["content"]->io.swagger.v3.oas.models.media.Content["null"])
        at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:283)
        at com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1366)
        at com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1262)
        at com.fasterxml.jackson.databind.ser.impl.FailingSerializer.serialize(FailingSerializer.java:32)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeOptionalFields(MapSerializer.java:868)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeWithoutTypeInfo(MapSerializer.java:760)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:720)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:35)
...
```
**Steps to reproduce:**
1. Create a ballerina package with `book_store`
2. Make it initialization with the `bal persist init --module store` 
3. Copy past below model.bal details into persist model
```ballerina
import ballerina/persist as _;

public type Book record {|
    readonly int id;
    string book_title;
    string author;
    string category;
    int published_year;
    decimal price;
    int copies_in_stock;
|};
```
4. Execute `bal persist generate`
5. Copy-paste ballerina service.bal[1] into package
6.  Execute the command `bal build --export-openapi`

**Affected Versions:**
2201.8.4
**OS, DB, other environment details and versions:**
Mac

**Comment by TharmiganK** [comment]
This is fixed with https://github.com/ballerina-platform/openapi-tools/pull/1564. The fix will be available in Ballerina SwanLake Update 9
