### ISSUE TITLE
[HTTP] Malformed query parameter leads to NPE

### ISSUE THREAD

**Issue by chamajay** [ballerina-platform/ballerina-library#6308]
**Description:**

This issue occurs when:
- The request query parameter is in the malformed format: `?foo` (without "=" and a value) 
- The query parameters are accessed using the [getQueryParams()](https://central.ballerina.io/ballerina/http/2.10.12#Request-getQueryParams) method of the `http:Request` class. 

`getQueryParams()` returns a `map<string[]>`. However, the actual value for the key 'foo' is null/nil. Any attempt to perform operations on this value as a `string[]` will result in an NPE, causing the service to crash. The HTTP module should be able to to handle this type of malformed query parameters properly.

As a workaround, users can explicitly change the type from `map<string[]>` to `map<string[]?>` and do a nil check beforehand.

I suggest handling this type of malformed query parameters similarly to how parameters like `?foo=` (without a value) are handled.

**Steps to reproduce:**

1. Run the following service:

```ballerina
import ballerina/http;

service / on new http:Listener(9090) {
    isolated resource function get hello(http:Request request) returns string? {
        map<string[]> params = request.getQueryParams();
        string[] fooValues = params.get("foo");
        return string `Hello, ${fooValues[0]}`;
    }
}

```

2. Invoke the resource method with the malformed query parameter:

```bash
curl --location 'http://localhost:9090/hello?foo'
```

This results in:

```
[2024-04-12 19:40:43,259] SEVERE {b7a.log.crash} - Cannot invoke "io.ballerina.runtime.internal.values.ArrayValue.getBString(long)" because "fooValues" is null 
java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.values.ArrayValue.getBString(long)" because "fooValues" is null
        at chamathjayasena.playground_service.0.$value$$anonType$_0.$get$hello(service.bal:7)
        at chamathjayasena.playground_service.0.$value$$anonType$_0.call(service.bal)
        at io.ballerina.runtime.internal.BalRuntime.lambda$getFunction$0(BalRuntime.java:258)
        at io.ballerina.runtime.internal.scheduling.SchedulerItem.execute(SchedulerItem.java:54)
        at io.ballerina.runtime.internal.scheduling.Scheduler.run(Scheduler.java:306)
        at io.ballerina.runtime.internal.scheduling.Scheduler.runSafely(Scheduler.java:273)
        at java.base/java.lang.Thread.run(Thread.java:833)

error: java.lang.NullPointerException: Cannot invoke "io.ballerina.runtime.internal.values.ArrayValue.getBString(long)" because "fooValues" is null
        at chamathjayasena.playground_service.0.$anonType$_0:$get$hello(service.bal:7)
```

**Affected Versions:**
4.10.12

**OS, DB, other environment details and versions:**
Windows 10
Ballerina 2201.8.6 (Swan Lake Update 8)

**Related Issues (optional):**

**Suggested Labels (optional):**

module/http

**Suggested Assignees (optional):**

**Comment by TharmiganK** [comment]
It seems there is an bug when returning the query map from the java native side. The return type of the `getQueryParams` function should be `map<string[]?>`.

@chamajay as a workaround you could use the `getQueryParamValues` function instead, which does the nil check beforehand:
```bal
import ballerina/http;

service / on new http:Listener(9090) {
    isolated resource function get hello(http:Request request) returns string? {
        string[]? fooValues = request.getQueryParamValues("foo");
        return fooValues is () ? () : string `Hello, ${fooValues[0]}`;
    }
}
```
