### ISSUE TITLE
NPE in OpenAPI client generation

### ISSUE THREAD

**Issue by MaryamZi** [ballerina-platform/ballerina-library#6351]
**Description:**
$title.

```
[2024-04-18 09:08:25,630] SEVERE {b7a.log.crash} - Cannot invoke "java.util.Optional.isPresent()" because "dataType" is null 
java.lang.NullPointerException: Cannot invoke "java.util.Optional.isPresent()" because "dataType" is null
        at io.ballerina.openapi.core.generators.client.FunctionReturnTypeGeneratorImp.populateReturnType(FunctionReturnTypeGeneratorImp.java:130)
        at io.ballerina.openapi.core.generators.client.FunctionReturnTypeGeneratorImp.getReturnTypeInfo(FunctionReturnTypeGeneratorImp.java:112)
        at io.ballerina.openapi.core.generators.client.FunctionReturnTypeGeneratorImp.getReturnType(FunctionReturnTypeGeneratorImp.java:80)
        at io.ballerina.openapi.core.generators.client.ResourceFunctionSignatureGenerator.generateFunctionSignature(ResourceFunctionSignatureGenerator.java:90)
        at io.ballerina.openapi.core.generators.client.ResourceFunctionGenerator.getFunctionDefinitionNode(ResourceFunctionGenerator.java:107)
        at io.ballerina.openapi.core.generators.client.ResourceFunctionGenerator.generateFunction(ResourceFunctionGenerator.java:75)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.addResourceFunction(BallerinaClientGenerator.java:609)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.createResourceFunctions(BallerinaClientGenerator.java:598)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getClassDefinitionNode(BallerinaClientGenerator.java:253)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.getModuleMemberDeclarationNodes(BallerinaClientGenerator.java:209)
        at io.ballerina.openapi.core.generators.client.BallerinaClientGenerator.generateSyntaxTree(BallerinaClientGenerator.java:193)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClientFiles(BallerinaCodeGenerator.java:396)
        at io.ballerina.openapi.cmd.BallerinaCodeGenerator.generateClient(BallerinaCodeGenerator.java:241)
        at io.ballerina.openapi.cmd.OpenApiCmd.generatesClientFile(OpenApiCmd.java:403)
        at io.ballerina.openapi.cmd.OpenApiCmd.openApiToBallerina(OpenApiCmd.java:328)
        at io.ballerina.openapi.cmd.OpenApiCmd.execute(OpenApiCmd.java:229)
        at java.base/java.util.Optional.ifPresent(Optional.java:178)
        at io.ballerina.cli.launcher.Main.main(Main.java:58)
```

**Steps to reproduce:**
- Schema from https://help.opendatasoft.com/apis/ods-explore-v2/explore_v2.1.html with L86 updated to "application/json" due to https://github.com/ballerina-platform/ballerina-library/issues/6343
- Command - `bal openapi -i openapi.json --mode client -o client_pkg --operations getDatasets`

**Affected Versions:**
2201.9.0 test pack

**Comment by lnash94** [comment]
This issue is already fixed with https://github.com/ballerina-platform/openapi-tools/pull/1676
