### ISSUE TITLE
Enable `testCodeActions` tests in websub for java 21

### ISSUE THREAD

**Issue by HindujaB** [ballerina-platform/ballerina-library#7373]
### Description

$subject 
This was disabled due to an OOM error. 
```
io.ballerina.stdlib.websub.codeaction.MandatoryFunctionsGenerationActionTest > testCodeActions[0](service.bal, 19, 8, result.bal) FAILED
    java.lang.OutOfMemoryError at Arrays.java:3482
```
https://github.com/ballerina-platform/module-ballerina-websub/actions/runs/11896654193/job/33149048234

**Comment by ayeshLK** [comment]
Tested this failure locally and was able to get the complete stacktrace:

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Arrays.copyOf(Arrays.java:3482)
	at java.base/java.util.ArrayList.grow(ArrayList.java:237)
	at java.base/java.util.ArrayList.grow(ArrayList.java:244)
	at java.base/java.util.ArrayList.add(ArrayList.java:483)
	at java.base/java.util.ArrayList.add(ArrayList.java:496)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parseCompUnit(BallerinaParser.java:460)
	at io.ballerina.compiler.internal.parser.BallerinaParser.parse(BallerinaParser.java:102)
	at io.ballerina.compiler.syntax.tree.SyntaxTree.from(SyntaxTree.java:63)
	at io.ballerina.stdlib.websub.action.MandatoryFunctionsGenerationAction.execute(MandatoryFunctionsGenerationAction.java:97)
	at io.ballerina.projects.CodeActionManager.executeCodeAction(CodeActionManager.java:131)
	at io.ballerina.stdlib.websub.codeaction.AbstractCodeActionTest.executeCodeAction(AbstractCodeActionTest.java:153)
	at io.ballerina.stdlib.websub.codeaction.AbstractCodeActionTest.performTest(AbstractCodeActionTest.java:92)
	at io.ballerina.stdlib.websub.codeaction.AbstractCodeActionTest.testCodeActions(AbstractCodeActionTest.java:64)
	at java.base/java.lang.invoke.LambdaForm$DMH/0x00007d51e43cb000.invokeVirtual(LambdaForm$DMH)
	at java.base/java.lang.invoke.LambdaForm$MH/0x00007d51e43d7400.invoke(LambdaForm$MH)
	at java.base/java.lang.invoke.Invokers$Holder.invokeExact_MT(Invokers$Holder)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invokeImpl(DirectMethodHandleAccessor.java:157)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
	at org.testng.TestRunner$$Lambda/0x00007d51e41587a8.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at org.testng.TestRunner.privateRun(TestRunner.java:829)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
```

And it seems like it is coming from the `SyntaxTree` API.

**Comment by ayeshLK** [comment]
Heap dump for the build:
[java_pid29690.zip](https://github.com/user-attachments/files/17861666/java_pid29690.zip)

**Comment by rdulmina** [comment]
@ayeshLK  I had a look @ the heap dump. Although the stacktrace contains parser classes, heap dump does not contain any evidence to support that. @warunalakshitha @HindujaB can u have a look @ this

**Comment by HindujaB** [comment]
@rdulmina 
From the heapdump provided, an object instance of `Object[]` is causing the OOM error. When checking the reference, it contains around 10000 elements of `STMetadataNode` each includes a set of other nodes. 
This could be probably from a recursion from parser side. But it didn't have any self reference in the object. 
<img width="1268" alt="Screenshot 2024-11-22 at 13 44 19" src="https://github.com/user-attachments/assets/657f5394-ffa9-4287-ab10-df8bff506f3b">

<img width="1280" alt="Screenshot 2024-11-22 at 13 40 18" src="https://github.com/user-attachments/assets/83735b5b-5bd7-4c86-a912-6a758cb5d878">

**Comment by ayeshLK** [comment]
@lochana-chathura do you have any idea about this ?
